version: '2'
services:
  magento:
    build: ./php
    ports:
      - '80:80'
    volumes:
      - ./html:/var/www/html
    links:
      - mysql
      - redis

  redis:
    image: redis
    ports:
      - '6379:6379'

  mysql:
    build: ./mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: ivory
      MYSQL_PASSWORD: ivory
